### ISSUE TITLE
Can page-object handle tags under SVG?

### ISSUE THREAD

**Issue by lgould** [cheezy/page-object#364] opened 2016-04-20 13:51 UTC
I tried to use element(:custom_name, :g, css: 'css_selector') to interact with a "g" element, but got an error: undefined method `g'

A main feature of the app that I'm automating are mostly Scalable Vector Graphics, which means, I'll need to interact with "g, rect, circle, text" etc. I know that page-object has a ready to use svg( ) method, I don't see others in rubydoc.info site. Can anyone advise?

**Comment by Cohen-Carlisle** [comment] 2016-04-21 01:17
Can you double check your code?
It sounds like you left off the `:` and ruby is trying to find a method named `g`.
I,e, you wrote:
```ruby
element(:custom_name, g, css: 'css_selector)
```

**Comment by lgould** [comment] 2016-04-21 01:52
Good observation. I typed it out wrong , I actually did use ":" in front of the g, like this: element(:custom_name, :g, css: 'css_selector')

**Comment by Cohen-Carlisle** [comment] 2016-04-21 02:11
I'm not able to reproduce this. I can interact with `g` elements in the manner in which you described.
For example, if I create this class:
```ruby
class Foo
  include PageObject
  element(:foo, :g, css: 'body > svg:nth-child(1) > g:nth-child(1)')  
end
```
It can locate the `g` element in this HTML:
```html
<svg viewBox="0 0 95 50"
     xmlns="http://www.w3.org/2000/svg">
   <g stroke="green" fill="white" stroke-width="5">
     <circle cx="25" cy="25" r="15"/>
     <circle cx="40" cy="25" r="15"/>
     <circle cx="55" cy="25" r="15"/>
     <circle cx="70" cy="25" r="15"/>
   </g>
</svg>
```
Like this:
```ruby
on(Foo).foo_element.visible?
```

This is using page object 1.1.1, I'm not sure what old versions are doing.

**Comment by lgould** [comment] 2016-04-21 13:07
That's what I suspected. I have page-object (1.0.3) and watir-webdriver (0.6.11).  May I ask what version of watir-webdriver do you have, or do you use selenium-webdriver? If you use watir, can you check if you have the following code in this file: 
[USER_PATH]/.rvm/gems/ruby-2.1.4/gems/watir-webdriver-0.6.11/lib/watir-webdriver/elements/generated.rb 
(need to replace your ruby version and watir version accordingly in the path)

def g(*args)
        G.new(self, extract_selector(args).merge(:tag_name => "g"))
end

def gs(*args)
       GCollection.new(self, extract_selector(args).merge(:tag_name => "g"))
end

**Comment by jkotests** [comment] 2016-04-21 13:58
Sounds like the problem is that you are using an old version of Watir-Webdriver. Support for SVG elements was not added until [version 0.8.0](https://github.com/watir/watir-webdriver/blob/master/CHANGES.md#080-2015-06-26).

**Comment by lgould** [comment] 2016-04-21 16:47
I see. OK, I'll try to upgrade it to version 0.8.0 and see.

**Comment by lgould** [comment] 2016-04-21 17:49
Upgrading watir webdriver to v0.8.0 solved the <g><rect><circle> tags recognition issue. Except the <text> tag under the SVG group was still not defined in svg_element.rb. Has anybody used this tag successfully using the watir/page-object framework? I can monkey patch it in, but would like to hear any good suggestions from others first. Thanks.

**Comment by cheezy** [comment] 2016-05-31 13:15
You can access the `text` method on the element itself.  For example, given the code in the examples above you could call the `custom_name_element` method which would return a generic `Element` object that has a `text` method.  This should work.

**Comment by cheezy** [comment] 2016-10-31 23:24
A new release is coming out very soon that adds support for all of the missing svg elements.  Take a look at git to see what is coming.  g is supported as well a circle.  I'm going to close this issue but reopen if you feel it needs more attention.

**Closed by cheezy** 2016-10-31 23:24 UTC
