### ISSUE TITLE
Differnt present? methods are called when using element.present? and element.when_present

### ISSUE THREAD

**Issue by taolinqu** [cheezy/page-object#470] opened 2018-11-12 18:52 UTC
I am using the follwing lines in my PageObject class:

radio_button(:your_name, :id => 'an_id')

def do_work
  your_name_element.present?
  your_name_element.when_present
end

I was confused when when_present is always timed out but present? always returns true.

I debugged and found out that:
your_name_element.present? is using the present? method defined in C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/activesupport-5.2.1/lib/active_support/core_ext/object/blank.rb.

In your_name_element.when_present call, there is a call to present? method as well. But the present? method is defined in C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/watir-6.14.0/lib/watir/elements/element.rb

I am using latest PageObject gem which is 2.2.4.

**Comment by jkotests** [comment] 2018-11-12 20:05
This is caused by ActiveSupport adding Object#present?. PR #466 has been opened to address this.

**Comment by taolinqu** [comment] 2018-11-12 21:07
:+1:
Thank you @jkotests 
Waiting for the merge of your PR

**Comment by soumyaray** [comment] 2018-11-16 06:07
no commits or PRs accepted in a year — is this project still maintained?

**Comment by jkotests** [comment] 2018-11-20 15:32
@taolinqu , @soumyaray , PR #466 is now merged. A release will go out in the next day or two.

**Closed by jkotests** 2018-11-20 15:32 UTC
