### ISSUE TITLE
Need an input types email and password

### ISSUE THREAD

**Issue by lauravachon** [cheezy/page-object#335] opened 2015-10-06 20:13 UTC
need an email_field element which is an input field of type email, very similar to text input field
need a password_field element which is an input type of password, very similar to text input field
![elementtypeemail](https://cloud.githubusercontent.com/assets/13202312/10321155/2a439ad2-6c45-11e5-9f38-bfdda6ab9312.png)

**Comment by Donavan** [comment] 2015-10-07 20:33
Can't you just grab it by it's ID?

**Comment by morozgrafix** [comment] 2015-10-08 10:17
Give this a try:
```ruby
class PaypalSignInPage
  include PageObject
  page_url = 'https://www.paypal.com/signin'
  text_field(:email, :id => 'email')
  text_field(:password, :id => 'password')
  button(:btn_login, :id => 'btnLogin')
```

and then use something along those lines:

```ruby
visit(PaypalSignInPage)
@current_page.email = 'foo@bar.com'
@current_page.password = 'pa55w0rd'
@current_page.btn_login
```

**Comment by lauravachon** [comment] 2016-02-08 20:47
Yeah, that was not working for email or password. Not sure why. Running into this on google now.

**Comment by uscengineer** [comment] 2016-02-08 22:04
Could it be that it is not waiting for the email text field to be available?
Try this
``
visit(PaypalSignInPage) do |page|
  page.email_element.when_present.value = 'foo@bar.com'
  page.password = 'pa55w0rd'
  page.btn_login
end
``

**Comment by entwanderer** [comment] 2016-09-27 08:05
I guess i found the problem

**implicit text_field method inside the page object not working with selenium driver at some cases**

I had an issue, that i could not fill text fields using page-object, but it worked when using the selenium driver directly. After some analyzing i figured out, that it works with page-object as well, when i explicit use the self variant.

The same problem encountered once, but not reproduceable, when the type of the input was "email". Currently the problem occurs all the time.



```
  text_field(:login_email, :id => "email")
  text_field(:login_password, :id => "password")

  # should work, but is NOT working!
  def login(email,password)
    login_email = email
    login_password = password
  end

  # working!
  def login_self(email,password)
    self.login_email = email
    self.login_password = password
  end
```

I created a simple cucumber project for demonstration - there you can see the working and not working solution:
https://github.com/entwanderer/page-object_text_field_bug

**Comment by entwanderer** [comment] 2016-09-27 08:13
is this a bug?

**implicit text_field method inside the page object not working with selenium driver at some cases**

I had an issue, that i could not fill text fields using page-object, but it worked when using the selenium driver directly. After some analyzing i figured out, that it works with page-object as well, when i explicit use the self variant.

```
text_field(:login_email, :id => "email")
text_field(:login_password, :id => "password")

# should work, but is NOT working!
def login(email,password)
  login_email = email
  login_password = password
end

# working!
def login_self(email,password)
  self.login_email = email
  self.login_password = password
end
```

**Comment by vveliev** [comment] 2016-09-27 14:54
this is ruby, and strictly speaking you should always use self.

**Comment by Cohen-Carlisle** [comment] 2016-09-28 01:36
Its not a bug. Let's break it down.
```ruby
text_field(:login_email, :id => "email")
```
This code snippet above defines multiple methods on the class, but the one of interest is `login_email=`.
```ruby
def login(email,password)
  login_email = email
  login_password = password
end
```
The above code snippet never calls the method `login_email=` on the instance of the class (`self`), which is what you want it to do. Remember that `self.login_email = email` is syntactic sugar for `self.login_emal=(email)`. Instead, it assigns a local variable `login_email`. This is a property of ruby's interpreter. Simply put, it will assign the variable before trying to call the method. To get around this, an explicit receiver is needed.
```ruby
def login_self(email,password)
  self.login_email = email
  self.login_password = password
end
```
That's why the above works. It uses an explicit receiver (`self`) and calls the method `login_email=` on it.

**Comment by entwanderer** [comment] 2016-09-28 05:46
I thank you both very much for your responds.

My expectation was, that a defined method has always higher priority to be called than a variable assignment. And  i still guess, that's the fact. But it seems that that is not happening here. I'd like to understand the whole scope.

For example 
```
 login_email_element.click
```
works fine without the self prefix.

So i can assume, that methods for text_fields are created on the fly and are not pre created like the *_element method? And therefore the interpreter can only go the way for variable assignment?

**Comment by Cohen-Carlisle** [comment] 2016-09-30 01:47
> My expectation was, that a defined method has always higher priority to be called than a variable assignment. And i still guess, that's the fact.

The problem is that the opposite is true. Local variable assignment happens before trying to find a reciever for any method ending in `=`.
You can verify this with some very simple code without even involving page-object:
```ruby
irb(main):001:0> defined?(foo)
=> nil
irb(main):002:0> def foo=(*args)
irb(main):003:1> puts "i called `foo=` with args=#{args}"
irb(main):004:1> end
=> :foo=
irb(main):005:0> foo=(5)
=> 5
irb(main):006:0> defined?(foo)
=> "local-variable"
irb(main):007:0> puts foo
5
=> nil
irb(main):008:0> self.foo = "hi"
i called `foo=` with args=["hi"]
=> "hi"
```
> So i can assume, that methods for text_fields are created on the fly and are not pre created like the *_element method? And therefore the interpreter can only go the way for variable assignment?

Nope. The `foo_element` and `foo=` methods are both created at the same time. Ruby simply will not call `foo=` without an explicit receiver. Its a bit confusing because the only time this ends up being a problem is from within the same class that defines `foo=`.

Does that clear it up?

**Comment by entwanderer** [comment] 2016-10-06 20:23
Ahhhh ... i see! Thank you very much for your example that cleared it all up ... 👍

**Comment by cheezy** [comment] 2016-11-04 18:43
I'm going to go ahead and close this issue as I believe everything is working.  Please reopen with comments if you disagree.

**Closed by cheezy** 2016-11-04 18:43 UTC
