### ISSUE TITLE
invalid 'in' operand a (Selenium::WebDriver::Error::JavascriptError)

### ISSUE THREAD

**Issue by ajubayer** [cheezy/page-object#261] opened 2015-01-21 00:03 UTC
error msg: invalid 'in' operand a (Selenium::WebDriver::Error::JavascriptError)
I was trying to get the html source within a web element so I defined the locator in lets say (xyz) and then called xyz_element.html to get the html source.
And I am getting the above error msg. 

It was working before and just started seeing this error msg from last week. Any idea?

I was able to find out a workaround so anyone with similar issue can do the following:
src = xyz_element.attribute('innerHTML')

**Comment by jkotests** [comment] 2015-01-21 02:22
Are you using Firefox? My guess is that these problems started happening last week after upgrading to Firefox 35.0. There have been various JavascriptError issues reported for Selenium-Webdriver with Firefox 35.0. At the moment, I believe the only solution is to downgrade your version of Firefox.

**Comment by yuri-karpovich** [comment] 2015-01-21 07:32
I can confirm that the problem is in FF 35.0. Downgrade to the previous FF version is the simplest way to solve it. 
You can find one of the previous Firefox versions in your local cache, for example:

      apt-cache showpkg firefox

and then install it from cache:

      $sudo apt-get install firefox=28.0+build2-0ubuntu2

**Comment by ajubayer** [comment] 2015-01-21 14:55
yes, i am using ff 35

**Comment by carlositocasal** [comment] 2015-02-03 06:34
+1

**Comment by cheezy** [comment] 2015-02-25 00:07
Was this just an issue with FF 35?

**Comment by mnohai-mdsol** [comment] 2015-04-02 13:08
Also is it in the latest version of selenium-webdriver 2.45?

**Comment by daneandersen** [comment] 2015-04-22 00:22
Has this issue been resolved or is it still occurring?

**Comment by daneandersen** [comment] 2015-05-05 19:24
I am going to close this since it seems to have passed. Feel free to re-open the issue if you are still experiencing this issue.

**Closed by daneandersen** 2015-05-05 19:24 UTC
